name: PickyTrees
description: Trees are picky where they grow and prefer their native biomes.
author: Raus
main: com.raus.pickyTrees.Main
version: 1.0
api-version: 1.15

commands:
  picky:
    description: Picky trees
    default: true
    usage: "Usage: /picky [info|reload]"

permissions:
  picky.reload:
    default: op
    description: Allows you to reload the config